export const articles = [
  {
    title: "When Was the Last Time Your Tires Were Rotated and Balanced?",
    slug: "when-was-the-last-time-your-tires-were-rotated-and-balanced",
    category: "General",
    date: "09/02/2025",
    read: "2 min read",
    author: "JPSPARE Experts",
    excerpt: "Tires are a critical safety component of your vehicle, and their condition directly impacts performance, handling, and fuel efficiency.",
    image: "/blog-tire-rotation-balancing.jpeg",
    position: "center",
    tag: "Maintenance",
    views: "1.8k",
    saves: 234,
    likes: 156,
    downloads: 67,
    summary: "Regular tire rotation and balancing helps your vehicle stay stable, protects tread life, and keeps everyday driving safer.",
    sections: [
      ["Why tire rotation matters", "Front and rear tires wear differently because steering, braking, weight transfer, and road conditions place different loads on each wheel. Rotating tires helps even out that wear and keeps handling predictable."],
      ["When to check balancing", "If you feel steering vibration, uneven tread wear, or shaking at highway speed, your wheels may need balancing. A quick inspection can prevent extra stress on suspension parts."],
      ["What drivers should inspect", "Look for uneven tread depth, sidewall damage, low pressure, and unusual noise. These signals often appear before a larger safety or performance issue."],
      ["Keep a maintenance rhythm", "Most drivers benefit from checking tire condition during regular service intervals. Pairing rotation with pressure checks and alignment inspections keeps the vehicle more reliable."],
    ],
  },
  {
    title: "10 Road Safety Tips for Driving Your Car in the Rain",
    slug: "10-road-safety-tips-for-driving-your-car-in-the-rain",
    category: "General",
    date: "06/26/2025",
    read: "3 min read",
    author: "JPSPARE Experts",
    excerpt: "Driving during the rainy season can be stressful. Wet roads, poor visibility, and unexpected traffic require extra care.",
    image: "/black-odor-red-console.jpg",
    position: "center",
    tag: "Safety",
    views: "2.3k",
    saves: 198,
    likes: 142,
    downloads: 74,
    summary: "Rainy weather changes visibility, braking distance, and driver reaction time. A few careful habits can make every wet-road trip safer.",
    sections: [
      ["Check the condition of your vehicle", "Before you start your journey, make sure your vehicle is in top condition. Pay attention to fluids, brakes, tires, wipers, and lights."],
      ["Maintain a safe distance", "Wet roads increase braking distance. Keep extra space between your vehicle and the one in front so you have more time to react."],
      ["Avoid damaged roads", "Flooded or pothole-ridden roads can cause wheel damage, waterlogging, or electrical issues. Check weather and traffic advisories before a long drive."],
      ["Control your speed", "Drive at a steady pace that lets you brake gently and respond calmly. Lower speed also reduces the chance of hydroplaning."],
      ["Keep visibility clear", "Use working wipers, clean glass, and proper lighting. If windows fog up, use ventilation and a microfiber cloth to restore visibility quickly."],
    ],
  },
  {
    title: "Changing Engine Oil",
    slug: "changing-engine-oil",
    category: "General",
    date: "10/27/2022",
    read: "4 min read",
    author: "Routine Systems",
    excerpt: "Changing your vehicle's engine oil is not difficult, but it must be done properly. Learn the correct steps and intervals.",
    image: "/japanparts-reference.png",
    position: "66% 45%",
    tag: "Maintenance",
    views: "1.5k",
    saves: 121,
    likes: 94,
    downloads: 45,
    summary: "Fresh engine oil protects moving parts, manages heat, and helps your engine perform smoothly through daily use.",
    sections: [
      ["Why oil condition matters", "Old oil loses its protective quality and can carry contaminants through the engine. Regular changes reduce friction and help protect internal components."],
      ["Choose the right oil", "Always match viscosity and specification with your vehicle requirement. Using the wrong oil can affect performance and long-term reliability."],
      ["Replace the filter", "A clean oil filter keeps contaminants from circulating. Replacing it during an oil change is a simple way to protect the engine."],
      ["Check after service", "After refilling, inspect the level, check for leaks, and confirm that the engine runs smoothly before driving."],
    ],
  },
  {
    title: "Replacing Brake Pads",
    slug: "replacing-brake-pads",
    category: "General",
    date: "10/27/2022",
    read: "5 min read",
    author: "Routine Systems",
    excerpt: "Replacing brake pads is not hard, but it is one job that must be done carefully. Know the warning signs before you replace.",
    image: "/accessory-wide-angle-holder.jpeg",
    position: "center",
    tag: "Brake Parts",
    views: "1.2k",
    saves: 109,
    likes: 88,
    downloads: 39,
    summary: "Brake pads are a major safety component. Timely replacement keeps stopping performance consistent and prevents rotor damage.",
    sections: [
      ["Know the warning signs", "Squealing, grinding, longer stopping distance, or vibration can indicate worn pads. Inspect the system before the issue gets worse."],
      ["Use compatible parts", "Choose pads that match your vehicle and driving style. Poor fitment can reduce braking performance and create noise."],
      ["Inspect related hardware", "Check rotors, clips, caliper movement, and brake fluid condition while replacing pads."],
      ["Test carefully", "After installation, test braking at low speed first. Make sure the pedal feel is stable before normal driving."],
    ],
  },
  {
    title: "How to change oil filter",
    slug: "how-to-change-oil-filter",
    category: "General",
    date: "04/12/2023",
    read: "6 min read",
    author: "Routine Systems",
    excerpt: "Changing the fuel filter is part of regular maintenance. Keeping your fuel system properly maintained helps engine life.",
    image: "/accessory-car-shampoo.jpeg",
    position: "center",
    tag: "Engine Parts",
    views: "1.1k",
    saves: 87,
    likes: 73,
    downloads: 31,
    summary: "A clean filter supports proper flow and helps protect the engine from contamination during regular operation.",
    sections: [
      ["Prepare the vehicle", "Park safely, let the engine cool, and gather the correct replacement filter and tools before starting."],
      ["Remove carefully", "Loosen the old filter slowly and control spills with a drain pan. Check that the old gasket comes off with the filter."],
      ["Install the new filter", "Apply a light coat of clean oil to the gasket, fit the filter by hand, and tighten according to the recommended method."],
      ["Verify after startup", "Run the engine briefly, check for leaks, and recheck fluid level after the oil settles."],
    ],
  },
  {
    title: "How to Change Battery",
    slug: "how-to-change-battery",
    category: "General",
    date: "01/23/2023",
    read: "6 min read",
    author: "Routine Systems",
    excerpt: "Changing battery is not difficult, but it is one job that must be done safely. Learn the steps before replacing it.",
    image: "/accessory-yesido-wireless-holder.jpeg",
    position: "center",
    tag: "Troubleshooting",
    views: "1.4k",
    saves: 96,
    likes: 81,
    downloads: 36,
    summary: "Battery replacement needs simple but careful handling. Correct steps protect the vehicle electronics and improve starting reliability.",
    sections: [
      ["Confirm battery condition", "Check age, voltage, corrosion, and starting behavior. Make sure replacement is needed before removing the battery."],
      ["Disconnect safely", "Turn the vehicle off and remove the negative terminal first, then the positive terminal. Keep tools away from accidental contact."],
      ["Install the replacement", "Secure the new battery properly, connect positive first, then negative, and make sure the terminals are tight."],
      ["Check vehicle systems", "Start the vehicle and confirm lights, dashboard, and accessories work as expected."],
    ],
  },
];

export function getArticleBySlug(slug) {
  return articles.find((article) => article.slug === slug);
}
