export const frontendCategoryBlueprint = [
  {
    name: "Car Accessories",
    slug: "car-accessories",
    description: "Interior, exterior, electronics, care and lifestyle accessories.",
    sortOrder: 10,
    isFeatured: true,
    children: [
      { name: "Interior", slug: "interior", sortOrder: 10, children: ["Air Freshener", "Seat Covers", "Floor Mats"] },
      { name: "Exterior", slug: "exterior", sortOrder: 20, children: ["Car Cover", "Mud Guard", "Chrome Trim"] },
      { name: "Electronics", slug: "electronics", sortOrder: 30, children: ["Phone Holder", "Dash Camera", "Chargers"] },
      { name: "Car Care", slug: "car-care", sortOrder: 40, children: ["Wax", "Shampoo", "Washer Fluid"] },
      { name: "Utility", slug: "utility", sortOrder: 50, children: ["Organizer", "Tool Kit", "Storage"] },
      { name: "Safety", slug: "safety", sortOrder: 60, children: ["Emergency Kit", "Reflector", "First Aid"] },
      { name: "Performance", slug: "performance", sortOrder: 70, children: ["Cleaner", "Additive", "Filter Care"] },
      { name: "Lifestyle", slug: "lifestyle", sortOrder: 80, children: ["Perfume", "Decor", "Travel"] },
    ],
  },
  {
    name: "Car Parts",
    slug: "car-parts",
    description: "Genuine auto parts, electrical parts, filters, body parts and service essentials.",
    sortOrder: 20,
    isFeatured: true,
    children: [
      { name: "Brakes", slug: "brakes", sortOrder: 10, children: ["Brake Pad", "Brake Shoe", "Brake Fluid"] },
      { name: "Bulb", slug: "bulb", sortOrder: 20, children: ["HID", "LED", "Halogen"] },
      { name: "Tyre", slug: "tyre", sortOrder: 30, children: ["Car Tyre", "SUV Tyre"] },
      { name: "Electrical Parts", slug: "electrical-parts", sortOrder: 40, children: ["Ignition Coil", "AC Fuel Pump", "Head Light Set"] },
      { name: "Filter", slug: "filter", sortOrder: 50, children: ["Air Filter", "Oil Filter", "A/C Filter"] },
      { name: "Car Care Item", slug: "car-care-item", sortOrder: 60, children: ["Car Wash", "Car Polish", "Car Cleaner", "Air Freshner"] },
      { name: "Body Parts", slug: "body-parts", sortOrder: 70, children: ["Windshield", "Modellista Body Kits", "WALD Body Kits", "Other Body Kits"] },
      { name: "Wiper Blade", slug: "wiper-blade", sortOrder: 80 },
      { name: "Horn", slug: "horn", sortOrder: 90 },
      { name: "Battery", slug: "battery", sortOrder: 100 },
      { name: "Spark Plug", slug: "spark-plug", sortOrder: 110 },
      { name: "Shock Absorber", slug: "shock-absorber", sortOrder: 120 },
      { name: "Engine Parts", slug: "engine-parts", sortOrder: 130 },
    ],
  },
  {
    name: "Tyres",
    slug: "tyres",
    description: "Premium tyres by type, brand, care and rim size.",
    sortOrder: 30,
    isFeatured: true,
    children: [
      { name: "Car Tyre", slug: "car-tyre", sortOrder: 10 },
      { name: "SUV Tyre", slug: "suv-tyre", sortOrder: 20 },
      { name: "Performance Tyre", slug: "performance-tyre", sortOrder: 30 },
      { name: "Tyre Care", slug: "tyre-care", sortOrder: 40 },
      {
        name: "Tyres By Brand",
        slug: "tyres-by-brand",
        sortOrder: 50,
        children: ["Yokohama", "Bridgestone", "Pirelli", "Goodyear", "Michelin", "Dunlop", "Maxxis", "Continental", "Hankook", "Other Brands"],
      },
      {
        name: "Rim Size",
        slug: "rim-size",
        sortOrder: 60,
        children: ["13 Inch", "14 Inch", "15 Inch", "16 Inch", "17 Inch", "18 Inch", "19 Inch", "20 Inch", "21 Inch", "22 Inch"],
      },
    ],
  },
  {
    name: "Lubricant",
    slug: "lubricant",
    description: "Engine oil, transmission fluid, coolant and lubricant brand collections.",
    sortOrder: 40,
    isFeatured: true,
    children: [
      { name: "Engine Oil", slug: "engine-oil", sortOrder: 10, children: ["5W-30", "0W-20", "5W-40", "0W-40", "10W-30", "10W-40", "20W-50"] },
      { name: "Transmission Fluid", slug: "transmission-fluid", sortOrder: 20, children: ["ATF", "CVT Fluid", "Manual Trans"] },
      { name: "Coolant", slug: "coolant", sortOrder: 30, children: ["Ready-to-Use", "Concentrate", "Universal"] },
      { name: "Additives Fluid", slug: "additives-fluid", sortOrder: 40 },
      { name: "Lubricant By Brand", slug: "lubricant-by-brand", sortOrder: 50, children: ["ELF", "Shell", "Mobil 1", "Liqui Moly", "Ravenol", "Totachi", "Idemitsu", "Other Brands"] },
    ],
  },
  {
    name: "Service Essentials",
    slug: "service-essentials",
    description: "Common maintenance and service replacement items.",
    sortOrder: 50,
    isFeatured: true,
    children: [
      { name: "Air Filter", slug: "service-air-filter", sortOrder: 10 },
      { name: "Oil Filter", slug: "service-oil-filter", sortOrder: 20 },
      { name: "Fuel Pump", slug: "fuel-pump", sortOrder: 30 },
      { name: "Horn", slug: "service-horn", sortOrder: 40 },
    ],
  },
];
